logging:
  level:
    org.springframework.web: DEBUG
    ru.multicon: DEBUG


spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://localhost:35432/pointclick
    username: pointclick
    password: passwordpointclick

server:
  port: 8081
